function resize(self)

% IMPORTANT: Need to make sure we save the current
% main figure units, set them to pels, then set them back at the end
% Some functions, like errordlg(), set them briefly to other things, and
% sometimes the resize callback gets called during this interval, and that
% causes the figure to get messed-up.

% get current units, save; set units to pels
units_before=get(self.fig_h,'units');
set(self.fig_h,'units','pixels');

% get basic dims
pos=get(self.fig_h,'position');
figure_width=pos(3);
figure_height=pos(4);

% get number of axes
axes_hs=self.axes_hs;
n=length(axes_hs);

% spec out sizes, given the figure width and height
%x_label_area_height=50;
% if verLessThan('matlab','8.4.0') ,  % aka R2014b, the first release of HG2
%     x_label_area_height=40;
% else
x_label_area_height=50;  % This looks better in all versions
%end    
y_label_area_width=50;
y_label_offset_width=40;  % distance in pels from y-axis to y-axis labels
bottom_button_height=30;
bottom_button_width=60;
%n_scroll_buttons=6;
%n_zoom_buttons=3;
%n_bottom_buttons=n_scroll_buttons+n_zoom_buttons;
%button_intergroup_space_width=80;
bottom_button_spacer_width=20;
above_scrollbar_pad_height=0;
below_scrollbar_pad_height=10;
scrollbar_height=15;
figure_right_pad_size=20;
figure_left_pad_size=20;
figure_top_pad_size=20;
figure_bottom_pad_size=20;
plot_area_width=figure_width ...
                -figure_left_pad_size ...
                -y_label_area_width ...
                -figure_right_pad_size ;
total_plot_area_height=figure_height ...
                       -figure_top_pad_size ...
                       -x_label_area_height ...
                       -above_scrollbar_pad_height ...
                       -scrollbar_height ...
                       -below_scrollbar_pad_height ...
                       -bottom_button_height ...
                       -figure_bottom_pad_size ;
interplot_pad_height=0;
if n==0
  plot_area_height=NaN;
else
  plot_area_height=floor((total_plot_area_height- ...
                          (n-1)*interplot_pad_height)/n);
end

% prevent errors for crazy-small resize
plot_area_width=max(1,plot_area_width);
plot_area_height=max(1,plot_area_height);

% resize buttons
button_tags={'to_start_button_h' ...
             'page_left_button_h' ...
             'step_left_button_h' ...
             'step_right_button_h' ...
             'page_right_button_h' ...
             'to_end_button_h' ...
             'zoom_way_out_button_h' ...
             'zoom_out_button_h' ...
             'zoom_in_button_h'}';
for i=1:length(button_tags)
  eval(sprintf('%s=findobj(self.fig_h,''tag'',''%s'');',...
               button_tags{i},...
               button_tags{i}));
end
set(to_start_button_h,...
    'position',...
    [figure_left_pad_size+...
       y_label_area_width+...
       (1-1)*(bottom_button_width+bottom_button_spacer_width),...
     figure_bottom_pad_size,...
     bottom_button_width,...
     bottom_button_height]);
   
set(page_left_button_h,...
    'Position',...
    [figure_left_pad_size+...
       y_label_area_width+...
       (2-1)*(bottom_button_width+bottom_button_spacer_width),...
     figure_bottom_pad_size,...
     bottom_button_width,...
     bottom_button_height]);
set(step_left_button_h,...
            'Position',...
              [figure_left_pad_size+...
                 y_label_area_width+...
                 (3-1)*(bottom_button_width+bottom_button_spacer_width),...
               figure_bottom_pad_size,...
               bottom_button_width,...
               bottom_button_height]);
set(step_right_button_h,...
            'Position',...
              [figure_left_pad_size+...
                 y_label_area_width+...
                 (4-1)*(bottom_button_width+bottom_button_spacer_width),...
               figure_bottom_pad_size,...
               bottom_button_width,...
               bottom_button_height]);
set(page_right_button_h,...
            'Position',...
              [figure_left_pad_size+...
                 y_label_area_width+...
                 (5-1)*(bottom_button_width+bottom_button_spacer_width),...
               figure_bottom_pad_size,...
               bottom_button_width,...
               bottom_button_height]);
set(to_end_button_h,...
            'Position',...
              [figure_left_pad_size+...
                 y_label_area_width+...
                 (6-1)*(bottom_button_width+bottom_button_spacer_width),...
               figure_bottom_pad_size,...
               bottom_button_width,...
               bottom_button_height]);
set(zoom_way_out_button_h,...
            'Position',...
              [figure_width-figure_right_pad_size-...
                 (3)*bottom_button_width-...
                 (3-1)*bottom_button_spacer_width,...
               figure_bottom_pad_size,...
               bottom_button_width,...
               bottom_button_height]);
set(zoom_out_button_h,...
            'Position',...
              [figure_width-figure_right_pad_size-...
                 (2)*bottom_button_width-...
                 (2-1)*bottom_button_spacer_width,...
               figure_bottom_pad_size,...
               bottom_button_width,...
               bottom_button_height]);
set(zoom_in_button_h,...
            'Position',...
              [figure_width-figure_right_pad_size-...
                 (1)*bottom_button_width-...
                 (1-1)*bottom_button_spacer_width,...
               figure_bottom_pad_size,...
               bottom_button_width,...
               bottom_button_height]);

% resize axes, if there are any
tick_length_pels=5;
tick_length=tick_length_pels/max(plot_area_width,plot_area_height);
for i=1:n
  plot_axes_position=...
      [figure_left_pad_size+y_label_area_width,...
       figure_bottom_pad_size+ ...
         x_label_area_height+ ...
         above_scrollbar_pad_height+ ...
         scrollbar_height+ ...
         below_scrollbar_pad_height+ ...
         bottom_button_height+ ...
         (n-i)*plot_area_height+...
         (n-i)*interplot_pad_height,...
       plot_area_width,...
       plot_area_height];
  axes_hs_this=axes_hs(i);
  set(axes_hs_this,'position',plot_axes_position,...
                   'ticklength',tick_length*[1 2.5],...
                   'visible','on');
end

% resize the scrollbar
self.scrollbar.set_position([figure_left_pad_size+y_label_area_width ...
                             figure_bottom_pad_size+bottom_button_height+ ...
                               below_scrollbar_pad_height ...
                             plot_area_width ...
                             scrollbar_height]);

% put in the y-axis labels
if n>0
  units_pre=get(self.axes_hs(1),'units');
  set(self.axes_hs(1),'units','pixels');
  pos=get(self.axes_hs(1),'position');
  set(self.axes_hs(1),'units',units_pre);  
  axis_height=pos(4);
  y_pos=axis_height/2;
  for i=1:n
    y_label_h=get(self.axes_hs(i),'ylabel');
    set(y_label_h,'position',[-y_label_offset_width y_pos 1]);
    % this works because the units property of y_label_h is set to
    % 'pixels'
  end
end

% restore fig units
set(self.fig_h,'units',units_before);

end
