function result = new_named_tree(name, color, xyz, r, parent, tag_code) 
    result = struct('name', {name}, ...
                    'color', {color}, ...
                    'xyz', {xyz}, ...
                    'r', {r}, ...
                    'parent', {parent}, ...
                    'tag_code', {tag_code}) ;
end
