function result = preallocate_forest_of_named_trees(shape)
    result = struct_with_shape_and_fields(shape, ...
                                          {'name', ...
                                           'color', ...
                                           'xyz', ...
                                           'r', ...
                                           'parent', ...
                                           'tag_code'}) ;
end
