function save_swc_from_named_tree(file_name, named_tree)
    name = named_tree.name ;    
    color = named_tree.color ;    
    xyz = named_tree.xyz ;
    
    node_count = size(xyz,1) ;
    offset = mean(xyz,1) ;
    xyz_centered = bsxfun(@minus, xyz, offset) ;
    
    centered_swc_data = zeros(node_count,7) ;
    centered_swc_data(:,1) = (1:node_count)' ;
    centered_swc_data(:,2) = named_tree.tag_code ;        
    centered_swc_data(:,3:5) = xyz_centered ;
    centered_swc_data(:,6) = named_tree.r ;            
    centered_swc_data(:,7) = named_tree.parent ;            
    
    fid = fopen(file_name,'wt') ;
    fprintf(fid, '# Generated by save_swc_from_named_tree.m\n') ;
    fprintf(fid, '# OFFSET %24.17g %24.17g %24.17g\n', offset) ;
    fprintf(fid, '# COLOR %0.6f %0.6f %0.6f\n', color) ;
    fprintf(fid, '# NAME %s\n', name) ;
    fprintf(fid,'%d %d %24.17g %24.17g %24.17g %d %d\n',centered_swc_data') ;
    fclose(fid) ;
end
