function save_swc(file_name, tree_as_swc_array, tree_name, color)
    
    if ~exist('color', 'var') || isempty(color) , 
        hue = rand(1) ;
        saturation = 1 ;
        value = 0.9 ;  % Want to maintain some contrast against a white background
        color = hsv2rgb([hue saturation value]) ;
    end
    
    xyz = tree_as_swc_array(:,3:5) ;
    offset = mean(xyz,1) ;
    xyz_centered = bsxfun(@minus, xyz, offset) ;
    centered_swc_data = tree_as_swc_array ;
    centered_swc_data(:,3:5) = xyz_centered ;
    
    fid = fopen(file_name,'wt') ;
    fprintf(fid, '# Generated by save_swc.m\n') ;
    fprintf(fid, '# OFFSET %24.17g %24.17g %24.17g\n', offset) ;
    fprintf(fid, '# COLOR %0.6f %0.6f %0.6f\n', color) ;
    fprintf(fid, '# NAME %s\n', tree_name) ;
    fprintf(fid,'%d %d %24.17g %24.17g %24.17g %d %d\n',centered_swc_data') ;
    fclose(fid) ;
end
